spring.datasource.url=jdbc:h2:mem:smartledger;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Thymeleaf Template Engine
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
